### PR TITLE
Update operationID format and fix JS snippet generation

### LINKED ISSUE #484: Creating code samples from OpenAPI schema data
In #168, a new OpenAPI schema landed in this project, and will pave the way for a future where all the octokits have a shared schema! ❤️ 

Today I was inspecting the contents of the [openapi/api.github.com/operations](https://github.com/octokit/routes/tree/261c763e51ea4d327fedc51cde182d2ffec65708/openapi/api.github.com/operations) directory, and noticed that `operationId` values are all in snake-case format:

```
"operationId": "pulls-create-comment-reply"
```

It looks like these values are currently created by joining the `scope` and the `endpoint.idName` with a hyphen:

https://github.com/octokit/routes/blob/261c763e51ea4d327fedc51cde182d2ffec65708/lib/openapi.js#L193

I also noticed that there's already some code in this project for creating example code with `toShellExample` and `toJsExample`:

https://github.com/octokit/routes/blob/261c763e51ea4d327fedc51cde182d2ffec65708/lib/openapi.js#L261)

This leads me to a few questions:

- Do the generated code examples work yet? Based on the current implementation of `toJsExample` my guess is no:

https://github.com/octokit/routes/blob/261c763e51ea4d327fedc51cde182d2ffec65708/lib/openapi.js#L269

- Can we switch to using `operationId` values that more closely match the method names octokit clients will use? For example, I'd suggest that `pulls-create-comment-reply` should instead be `pulls.createCommentReply`

I'm happy to help out on this, but wanted to open this issue first to discuss and get a sense of where things are with this effort before jumping to an implementation.

cc @gr2m @d11n

### PR DESCRIPTION
**Pull request by zeke**
This PR updates the `operationIds` in the OpenAPI schema to use a dot `.` delimiter between scope names and function names, like `oauthAuthorizations.getGrant` instead of `oauth_authorizations-get-grant`

This PR also updates the `toJsExample` function to use the new `operationId`.

Note for reviewers: the meaningful commit is https://github.com/octokit/routes/pull/485/commits/a460d51e654977fd77f56d9b7fb84a270163c34c -- the rest of the changes are the result of running `./bin/octokit-rest-routes.js update`. Let me know if the results of running that script should be reverted from this PR.

Fixes #484

### CODE REVIEW

**Comment by d11n** [comment]
cool...i get you now on #484

i wouldn't use camelCase here because it is less straightforward to convert into another case...sdks being able to simply splitting on a hyphen is more straightforward than parsing a string for capital letters...not to mention more resilient to and consistent on acronyms and non-english characters, which *shouldn't* come into play here, but would be nice to know that downstream sdks won't have to negotiate `Oauth` vs `OAuth` vs `oAuth` vs `o_auth` vs `oauth`...as a general rule, i would use delimiters in machine names, especially if they're expected to be parsed and not just a unique identifier

my instincts are to keep the `operationId` more path-y, due to the api urls being the source of truth (and at the moment the docs urls too), as well as the added bonus that that's what the legacy `octokit/routes` consumers are using in the `idName`, which preceded the openapi-specific, globally-unique `operationId`

so to address the scope concern, i'd be more inclined to convert
```
pulls > create-comment-reply
oauth_authorizations > get-grant
```
into
```
pulls/create-comment-reply
oauth-authorizations/get-grant
```
and i'd enforce lowercase too for good measure...so `operationId`s that only differ on case would create an error in `octokit/routes` because that would be highly likely to trip up automation and/or developers in downstream sdks anyway

and thanks for updating the routes with the pr...it's necessary in this case to make the tests pass, so the pr can be merged

**Comment by gr2m** [comment]
> ```
> pulls/create-comment-reply
> oauth-authorizations/get-grant
> ```

I like that

**Comment by zeke** [comment]
Thanks for the feedback. I've updated `operationId` values to param-case with `/` as the delimiter, and preserved the camelCase format for the JS examples. 👍

**Comment by d11n** [comment]
see #505

**Comment by zeke** [comment]
Hey thanks! And apologies for not wrapping up this work earlier.

**Pull request closed without merging**
