### PR TITLE
Fix: missing responses for "Response if" blocks

### PR DESCRIPTION
**Pull request by RomanHotsiy**
Responses from "Response if" blocks were missing, e.g. https://developer.github.com/v3/orgs/members/#check-membership

### CODE REVIEW

**Comment by gr2m** [comment]
Looks good 👍 It would make it easier to review if you would separate the openapi update commit into

1. cache update
2. openapi files update

In fact I think I would remove the cache update altogether. You can run the update script with `--cached`, which will make it faster, too

**Comment by RomanHotsiy** [comment]
@gr2m is there a chance you can review it anytime soon? Thanks!

**Comment by gr2m** [comment]
Have you seen my comment above? https://github.com/octokit/routes/pull/521#issuecomment-527617643

It would help if you would split up the changes into commits in future. I can review it as is this time.

**Comment by RomanHotsiy** [comment]
@gr2m Ahh, sorry. I didn't get it. I though you are talking about the future PRs 🙈

Thanks for reviewing it the current shape 🙏

**Comment by gr2m** [comment]
No problem at all :)

**Pull request closed without merging**
